name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.AWS_PEM }}
          EC2_URL: ${{ secrets.EC2_URL }}

      - name: Run command on EC2
        run: |
          ssh $EC2_USERNAME@$EC2_URL "echo 'Hello from GitHub Actions' >> hello.txt"
