name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: ./AllergenCheckerApp
        run: flutter pub get

      - name: Build Flutter app
        working-directory: ./AllergenCheckerApp
        run: flutter build web --no-release

      - name: Set up SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.AWS_PEM }}
          EC2_URL: ${{ secrets.EC2_URL }}

      - name: Copy Build Files to EC2
        run: |
          scp -r ./AllergenCheckerApp/build/web/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }}:/var/www/html
          scp -r ./API/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }}:~/App
          
      - name: Start Backend Server
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} "chmod +x ./App/run.sh && ./App/run.sh"
